name: AI Knowledge Base (Working)

on:
  workflow_run:
    workflows: ["*"]
    types: [completed]

permissions:
  actions: read
  contents: write

jobs:
  ai-analyze-error:
    runs-on: ubuntu-latest
    if: |
      github.event.workflow_run.conclusion == 'failure' &&
      contains(github.event.workflow_run.name, 'ver') &&
      !contains(github.event.workflow_run.name, 'AI Knowledge Base')
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Debug
        run: |
          echo "## 🔍 Workflow Info" >> $GITHUB_STEP_SUMMARY
          echo "**Triggered by:** ${{ github.event.workflow_run.name }}" >> $GITHUB_STEP_SUMMARY
          echo "**Run ID:** ${{ github.event.workflow_run.id }}" >> $GITHUB_STEP_SUMMARY

      - name: Download log
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -L \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }}/logs" \
            -o current-log.zip
          
          if [ ! -f current-log.zip ]; then
            exit 1
          fi
          
          unzip -q current-log.zip -d current-log/
          find current-log/ -name "*.txt" -exec cat {} \; > full-log.txt
          
          TOTAL=$(wc -l < full-log.txt)
          echo "📊 Total: $TOTAL lines"
          
          EXIT_LINE=$(grep -n "exit code [1-9]" full-log.txt | head -n 1 | cut -d: -f1)
          
          if [ -z "$EXIT_LINE" ]; then
            EXIT_LINE=$(grep -n "##\[error\]" full-log.txt | head -n 1 | cut -d: -f1)
          fi
          
          if [ -n "$EXIT_LINE" ]; then
            START=$((EXIT_LINE - 3000))
            END=$((EXIT_LINE + 100))
            [ $START -lt 1 ] && START=1
            [ $END -gt $TOTAL ] && END=$TOTAL
            sed -n "${START},${END}p" full-log.txt > log-for-ai.txt
          else
            tail -n 5000 full-log.txt > log-for-ai.txt
          fi

      - name: Extract version
        id: extract_ver
        run: |
          VERSION=$(echo "${{ github.event.workflow_run.name }}" | grep -oE 'ver[0-9]+' || echo "ver-unknown")
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Call Gemini (FIX: Use file instead of argument)
        id: ai_analysis
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          # Create prompt with FULL 100KB context
          cat > prompt-text.txt << 'EOFPROMPT'
          Bạn là chuyên gia phân tích lỗi FFmpeg Android ARM32.
          
          WORKFLOW: Build FFmpeg Android ARM32 (Full Features + LibASS Added - ver8)
          VERSION: ver8
          
          CONTEXT:
          - ver8 đang build LibASS (subtitle renderer)
          - Thư viện OK: x264, x265, vpx, opus, lame, twolame, ogg, vorbis, theora, speex, gsm, fribidi, fdk-aac, aom, soxr, webp, freetype, openjpeg
          - Log dưới đây là context ĐẦY ĐỦ xung quanh exit code
          
          NHIỆM VỤ: Phân tích và trả về JSON:
          {
            "error_id": "ERROR-XXX",
            "error_name": "Mô tả chính xác",
            "root_cause": "Nguyên nhân gốc rễ",
            "affected_library": "libass",
            "error_type": "DEPENDENCY|LINKER|CONFIGURE|SYNTAX|UNKNOWN",
            "symptoms": ["lỗi chính xác"],
            "fix_suggestion": "Cách fix",
            "confidence": 90
          }
          
          LƯU Ý:
          - Trả về OBJECT {}, KHÔNG ARRAY
          - Tìm "Building LibASS" để xác định thư viện
          - Tìm "ERROR:" hoặc "error:" cho lỗi chính
          
          LOG (full context):
          
          EOFPROMPT
          
          # Append full log (up to 100KB = ~25K tokens)
          head -c 100000 log-for-ai.txt >> prompt-text.txt
          
          # Escape for JSON
          PROMPT_ESCAPED=$(jq -Rs . < prompt-text.txt)
          
          # Create JSON payload file (NOT in command argument!)
          cat > api-payload.json << EOFPAYLOAD
          {
            "contents": [{
              "parts": [{
                "text": $PROMPT_ESCAPED
              }]
            }],
            "generationConfig": {
              "temperature": 0.1,
              "maxOutputTokens": 2048,
              "responseMimeType": "application/json"
            }
          }
          EOFPAYLOAD
          
          echo "📤 Calling Gemini (payload from file)..."
          
          # CRITICAL FIX: Use @file instead of -d "..."
          RESP=$(curl -s -w "\nHTTP:%{http_code}" -X POST \
            "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-exp:generateContent?key=$GEMINI_API_KEY" \
            -H "Content-Type: application/json" \
            --data-binary @api-payload.json)
          
          HTTP=$(echo "$RESP" | tail -n 1 | cut -d: -f2)
          BODY=$(echo "$RESP" | sed '$d')
          
          echo "HTTP: $HTTP"
          
          if [ "$HTTP" != "200" ]; then
            echo "❌ API error"
            echo "$BODY" | jq . 2>/dev/null || echo "$BODY"
            cat > ai-analysis.json << 'EOF'
          {
            "error_id": "ERROR-999",
            "error_name": "API error",
            "root_cause": "Gemini failed",
            "affected_library": "unknown",
            "error_type": "API_ERROR",
            "symptoms": ["API error"],
            "fix_suggestion": "Retry",
            "confidence": 20
          }
          EOF
          else
            AI=$(echo "$BODY" | jq -r '.candidates[0].content.parts[0].text')
            
            if [ -z "$AI" ] || [ "$AI" = "null" ]; then
              cat > ai-analysis.json << 'EOF'
          {
            "error_id": "ERROR-998",
            "error_name": "Empty",
            "root_cause": "Empty",
            "affected_library": "unknown",
            "error_type": "API_ERROR",
            "symptoms": ["Empty"],
            "fix_suggestion": "Retry",
            "confidence": 15
          }
          EOF
            else
              echo "$AI" > ai-analysis-raw.json
              
              if echo "$AI" | jq -e 'type == "array"' > /dev/null 2>&1; then
                echo "$AI" | jq '.[0]' > ai-analysis.json
              else
                echo "$AI" > ai-analysis.json
              fi
              
              if ! jq empty ai-analysis.json 2>/dev/null; then
                cat > ai-analysis.json << 'EOF'
          {
            "error_id": "ERROR-997",
            "error_name": "Invalid JSON",
            "root_cause": "Parse error",
            "affected_library": "unknown",
            "error_type": "API_ERROR",
            "symptoms": ["Invalid"],
            "fix_suggestion": "Review",
            "confidence": 10
          }
          EOF
              fi
            fi
          fi
          
          cat ai-analysis.json
          
          echo "error_id=$(jq -r '.error_id // "ERROR-000"' ai-analysis.json)" >> $GITHUB_OUTPUT
          echo "error_name=$(jq -r '.error_name // "Unknown"' ai-analysis.json)" >> $GITHUB_OUTPUT
          echo "affected_lib=$(jq -r '.affected_library // "unknown"' ai-analysis.json)" >> $GITHUB_OUTPUT

      - name: Init KB
        run: |
          if [ ! -f .github/ERROR_KNOWLEDGE_BASE.md ]; then
            cat > .github/ERROR_KNOWLEDGE_BASE.md << 'EOF'
          # 📚 FFmpeg Android ARM32 - Error Knowledge Base

          > **AI:** Gemini với 100KB context  
          > **Tổng:** 0

          ## 📋 Quick Reference

          | ID | Lỗi | Thư viện | Ver | Ngày |
          |----|-----|----------|-----|------|

          ## 🔴 Chi tiết

          EOF
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add .github/ERROR_KNOWLEDGE_BASE.md
            git commit -m "docs: Init"
          fi

      - name: Add entry
        env:
          ERROR_ID: ${{ steps.ai_analysis.outputs.error_id }}
          ERROR_NAME: ${{ steps.ai_analysis.outputs.error_name }}
          AFFECTED_LIB: ${{ steps.ai_analysis.outputs.affected_lib }}
          VERSION: ${{ steps.extract_ver.outputs.version }}
        run: |
          JSON=$(cat ai-analysis.json)
          ROOT=$(echo "$JSON" | jq -r '.root_cause // "N/A"')
          TYPE=$(echo "$JSON" | jq -r '.error_type // "UNKNOWN"')
          FIX=$(echo "$JSON" | jq -r '.fix_suggestion // "N/A"')
          SYMP=$(echo "$JSON" | jq -r '.symptoms // ["N/A"] | join("\n- ")')
          CONF=$(echo "$JSON" | jq -r '.confidence // 0')
          
          sed -i "/^| ID/a | $ERROR_ID | $ERROR_NAME | $AFFECTED_LIB | $VERSION | $(date +%Y-%m-%d) |" .github/ERROR_KNOWLEDGE_BASE.md
          
          TOTAL=$(grep -c "^### 🔴" .github/ERROR_KNOWLEDGE_BASE.md 2>/dev/null || echo "0")
          NEW=$((TOTAL + 1))
          sed -i "s/Tổng:\*\* [0-9]*/Tổng:** $NEW/" .github/ERROR_KNOWLEDGE_BASE.md
          
          cat >> .github/ERROR_KNOWLEDGE_BASE.md << EOF

          ### 🔴 $ERROR_ID: $ERROR_NAME

          **📅** $(date +%Y-%m-%d) | **🔗** [Run #${{ github.event.workflow_run.run_number }}](https://github.com/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }})
          **🎯** \`$AFFECTED_LIB\` | **🏷️** \`$VERSION\` | **🤖** ${CONF}%

          **⚠️ Triệu chứng:**
          - $SYMP

          **🔍 Nguyên nhân:** $ROOT

          **🛠️ Fix:** $FIX

          **📝** \`$TYPE\`

          ---

          EOF

      - name: Commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .github/ERROR_KNOWLEDGE_BASE.md
          if ! git diff --staged --quiet; then
            git commit -m "🤖 ${{ steps.ai_analysis.outputs.error_id }} [${{ steps.extract_ver.outputs.version }}]"
            git push
          fi

      - name: Summary
        if: always()
        run: |
          echo "## ✅ Done" >> $GITHUB_STEP_SUMMARY
          echo "**Ver:** ${{ steps.extract_ver.outputs.version }}" >> $GITHUB_STEP_SUMMARY
          echo "**Error:** ${{ steps.ai_analysis.outputs.error_id }}" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`json" >> $GITHUB_STEP_SUMMARY
          cat ai-analysis.json 2>/dev/null || echo "{}"
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY

      - name: Cleanup
        if: always()
        run: rm -rf current-log/ current-log.zip full-log.txt log-for-ai.txt ai-analysis.json ai-analysis-raw.json prompt-text.txt api-payload.json 2>/dev/null || true
