name: Phân Tích Lỗi Định Kỳ

on:
  schedule:
    - cron: '0 0 * * 0'  # Chạy mỗi Chủ Nhật lúc 00:00
  workflow_dispatch:  # Cho phép chạy thủ công

permissions:
  actions: read
  contents: read

jobs:
  phan-tich-tong-hop:
    runs-on: ubuntu-latest
    steps:
      - name: Tải nhật ký lỗi
        uses: actions/download-artifact@v4
        with:
          name: error-log-database
          path: error-db/

      - name: Phân tích sâu
        run: |
          mkdir -p analysis
          
          echo "# BÁO CÁO PHÂN TÍCH LỖI TUẦN" > analysis/weekly-report.txt
          echo "Ngày: $(date)" >> analysis/weekly-report.txt
          echo "" >> analysis/weekly-report.txt
          
          TOTAL_ERRORS=$(grep -c "❌ LỖI BUILD" error-db/all-errors.txt || echo "0")
          echo "## Tổng quan" >> analysis/weekly-report.txt
          echo "- Tổng số lần build lỗi: ${TOTAL_ERRORS}" >> analysis/weekly-report.txt
          echo "" >> analysis/weekly-report.txt
          
          echo "## Phân loại lỗi" >> analysis/weekly-report.txt
          echo "" >> analysis/weekly-report.txt
          echo "### Lỗi liên quan đến thư viện:" >> analysis/weekly-report.txt
          grep -c "libass\|libfribidi\|libfreetype\|libfontconfig" error-db/all-errors.txt || echo "0" >> analysis/weekly-report.txt
          
          echo "" >> analysis/weekly-report.txt
          echo "### Lỗi linker:" >> analysis/weekly-report.txt
          grep -c "undefined reference" error-db/all-errors.txt || echo "0" >> analysis/weekly-report.txt
          
          echo "" >> analysis/weekly-report.txt
          echo "### Lỗi configure:" >> analysis/weekly-report.txt
          grep -c "not found\|No such file" error-db/all-errors.txt || echo "0" >> analysis/weekly-report.txt
          
          echo "" >> analysis/weekly-report.txt
          echo "## Khuyến nghị" >> analysis/weekly-report.txt
          echo "- Xem file gemini-context.txt để debug" >> analysis/weekly-report.txt
          echo "- Pattern lỗi lặp lại nhiều nhất cần fix ưu tiên" >> analysis/weekly-report.txt

      - name: Upload báo cáo
        uses: actions/upload-artifact@v4
        with:
          name: weekly-analysis-$(date +'%Y%m%d')
          path: analysis/
          retention-days: 30
